#!/usr/bin/env python3
import json
import os
import urllib.error
import urllib.parse
import urllib.request
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

DEFAULT_BIND = '0.0.0.0'
DEFAULT_PORT = 9999
DEFAULT_CONFIG_PATH = '/app/coco-runtime-config.json'
DEFAULT_HTML = (
    '<!DOCTYPE html><html><head><title>ZT Infra CoCo Produced HTML</title></head>'
    '<body><h1>Hello from CoCo workload</h1>'
    '<p>This page was generated by the CoCo workload-side wrapper.</p></body></html>'
)


def load_config() -> dict:
    path = Path(os.environ.get('COCO_RUNTIME_CONFIG_PATH', DEFAULT_CONFIG_PATH))
    if not path.exists():
        raise FileNotFoundError(f'Could not read CoCo runtime config: {path}')
    return json.loads(path.read_text())


def build_identity_hint(config: dict) -> str:
    return config.get('identity_hint') or (
        f"coco_image_initdata:{config['image_digest']}:{config['initdata_hash']}"
    )


def fetch_aa_evidence(aa_evidence_url: str, nonce_hex: str) -> object:
    parsed = urllib.parse.urlparse(aa_evidence_url)
    query = urllib.parse.parse_qsl(parsed.query, keep_blank_values=True)
    query = [(key, value) for key, value in query if key != 'runtime_data']
    query.append(('runtime_data', nonce_hex))
    url = urllib.parse.urlunparse(parsed._replace(query=urllib.parse.urlencode(query)))
    request = urllib.request.Request(url, headers={'Accept': 'application/json'})
    with urllib.request.urlopen(request, timeout=10) as response:
        payload = response.read().decode('utf-8')
    return json.loads(payload)


class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path != '/':
            self.send_error(404, 'not_found')
            return

        html = os.environ.get('COCO_INDEX_HTML', DEFAULT_HTML)
        body = html.encode('utf-8')
        self.send_response(200)
        self.send_header('Content-Type', 'text/html; charset=utf-8')
        self.send_header('Content-Length', str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_POST(self):
        if self.path != '/.well-known/attestation':
            self.send_error(404, 'not_found')
            return

        length = int(self.headers.get('Content-Length', '0'))
        try:
            body = json.loads(self.rfile.read(length) or b'{}')
        except json.JSONDecodeError:
            self.send_error(400, 'invalid_json')
            return

        nonce = body.get('NONCE')
        if not isinstance(nonce, str) or not nonce or any(ch not in '0123456789abcdefABCDEF' for ch in nonce) or len(nonce) % 2 != 0:
            self.send_error(400, 'invalid_nonce')
            return

        try:
            config = load_config()
            evidence = fetch_aa_evidence(config['aa_evidence_url'], nonce.lower())
        except (FileNotFoundError, KeyError, urllib.error.URLError, TimeoutError, json.JSONDecodeError) as error:
            self.send_error(502, str(error))
            return

        envelope = {
            'version': 'ztinfra-attestation/v1',
            'service': config['service'],
            'release_id': config['release_id'],
            'platform': config.get('platform', 'aws_coco_snp'),
            'nonce': nonce.lower(),
            'claims': {
                'workload_pubkey': config.get('workload_pubkey'),
                'identity_hint': build_identity_hint(config),
            },
            'evidence': {
                'type': 'coco_trustee_evidence',
                'payload': evidence,
            },
            'facts_url': config.get('facts_url'),
        }
        payload = json.dumps(envelope).encode('utf-8')
        self.send_response(200)
        self.send_header('Content-Type', 'application/json')
        self.send_header('Content-Length', str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def log_message(self, fmt, *args):
        print(f'[coco-wrapper] {self.address_string()} - {fmt % args}')


if __name__ == '__main__':
    host = os.environ.get('BIND_ADDR', DEFAULT_BIND)
    port = int(os.environ.get('PORT', str(DEFAULT_PORT)))
    server = ThreadingHTTPServer((host, port), Handler)
    print(f'CoCo wrapper listening on http://{host}:{port}')
    server.serve_forever()
